config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    ############################## READ
    get '/tasks' => 'tasks#index'
    # tasks#index tasks controller, index method
  
    ############################## CREATE
    # New - mauna kay show kasi top to bottom binabasa ang routes
    get '/tasks/new' => 'tasks#new', as: 'task_new'
    post '/tasks' => 'tasks#create'
  
    ############################## READ
    # Show by ID
    get '/tasks/:id' => 'tasks#show', as: 'task_show'
    # :id  -> route parameter
  
    ############################## UPDATE
    get '/task/:id/edit' => 'tasks#edit', as: 'task_edit' 
    put '/task/:id' => 'tasks#update', as: 'task_update' 
  
    ############################## DELETE
    delete '/task/:id' => 'tasks#delete', as: 'task_delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :person, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end
  # @variable - instance variable yung
  # naka-@ para maaccess sa labas ng class
  
  def show
    @task = Task.find(params[:id])
    # params hash-like
    # [:id] - key, supplied as symbol
  end

  def new
     @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
        redirect_to tasks_path, notice: 'Task was succesfully created.'
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was succesfully updated.'
    else
      render :edit
    end
  end

  def delete
    @task = Task.find(params[:id])

    @task.destroy
    redirect_to tasks_path, notice: 'Task was successfully deleted.'
  end

  private

  def task_params
    params.require(:task).permit(:person, :overview)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskListCrudApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with scope: :task, url: 'task_update_path', model: @task, method: :put, locale: true do |form| %>
  <h1> Edit Task </h1>
  <%= form.label :person %>
  <%= form.text_field :person %>

  <%= form.label :overview %>
  <%= form.text_field :overview %>
  
  <%= form.submit %>
  
<% end %>

app/views/tasks/index.html.erb
<h1 class="index-header"> Task List </h1>

<div class="index-table">
<table>
  <thead class="index-table-headers">
    <tr>
      <th class="index-header-id"> Task ID </th>
      <th class="index-header-player"> Person </th>
      <th class="index-header-username"> Overview </th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <div class="td-elements">
        <td class="index-element-id"> <%= task.id %> </td>
        <td class="index-element-title"> <%= task.person %> </td>
        <td class="index-element-body"> <%= task.overview %> </td>
        </div>
        <td>
          <button class= "index-btn">
            <%= link_to "Edit", task_edit_path(task.id) %>
          </button>
        </td>

        <td>
          <button class= "index-btn">
            <%= link_to "View", task_show_path(task.id) %>
          </button>
        </td>

        <td>
          <button class= "index-btn">
            <%= link_to "Delete", task_delete_path(task.id), method: :delete %>
          </button>
        </td>
      </tr>
    <% end %>

    <tr>
      <td>
        <button class= "index-new-btn">
          <%= link_to "New Task", task_new_path %>
        </button>
      </td>
    </tr>
  </tbody>
</table>
</div>

app/views/tasks/new.html.erb
<%= form_with scope: :task, model: @task, locale: true do |form| %>
  <h1> New Task </h1>
  <%= form.label :person %>
  <%= form.text_field :person %>

  <%= form.label :overview %>
  <%= form.text_field :overview %>
  
  <%= form.submit %>
  
<% end %>

app/views/tasks/show.html.erb
<h1>Task ID # <%= @task.id %> </h1>

<table>
  <thead>
    <tr>
      <th> Person </th>
      <th> Overview </th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td> <%= @task.person %> </td>
        <td> <%= @task.overview %> </td>
      </tr>
  </tbody>

  <td><%= link_to "Home", tasks_path %></td>
</table>